/* Generated by the Nim Compiler v2.0.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
/* line 240:5 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */

function toJSStr(s_33556901) {
  var result_33556902 = null;

    /* line 251:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
    var res_33556943 = newSeq_33556919((s_33556901).length);
    /* line 252:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
    var i_33556944 = 0;
    /* line 253:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
    var j_33556945 = 0;
    Label1: {
      /* line 254:2 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          /* line 255:8 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          /* line 257:27 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          /* line 258:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
          i_33556944 += 1;
          }
          else {
            /* line 260:10 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
              /* line 261:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                Label4: while (true) {
                if (!true) break Label4;
                  /* line 262:12 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  /* line 264:16 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  helper_33556959.push("%0");;
                  }
                  else {
                    /* line 266:16 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  helper_33556959.push("%");;
                  }
                  
                  /* line 267:14 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  helper_33556959.push(code_33556960);;
                  /* line 268:8 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  /* line 269:40 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  break Label3;
                  }
                  
                  /* line 270:13 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
                  c_33556946 = s_33556901[i_33556944];
                }
            };
            /* line 271:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
++excHandler;
            try {
            /* line 272:36 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            /* line 274:21 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          /* line 275:4 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
          j_33556945 += 1;
        }
    };
    /* line 276:8 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    /* line 277:15 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
    result_33556902 = res_33556943.join("");

  return result_33556902;

}
/* line 382:7 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */

function rawEcho() {
    /* line 383:4 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/jssys.nim" */
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
/* line 18:4 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/compilation.nim" */
var F = {procname: "module dom", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
/* line 218:6 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/hashes.nim" */
F.line = 218;
F.filename = "hashes.nim";
var objectID_754974897 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
/* line 45:2 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/jsffi.nim" */
F.line = 45;
F.filename = "jsffi.nim";
/* line 46:2 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/jsffi.nim" */
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nimponents", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nimponents", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim", line: 0};
framePtr = F;
framePtr = F.prev;
/* line 613:5 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system.nim" */

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system.nim", line: 0};
  framePtr = F;
    /* line 631:8 "/home/monofuel/Documents/src/monofuel34089/Nim/lib/system.nim" */
    F.line = 631;
    F.filename = "system.nim";
    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }  framePtr = F.prev;

  return result_33556922;

}
/* line 18:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */

function setupNimponent_536870953(elementName_536870955, constructor_536870957, connectedCallback_536870959, disconnectedCallback_536870961, adoptedCallback_536870963, attributeChangedCallback_536870968) {
  var F = {procname: "setupNimponent.setupNimponent", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim", line: 0};
  framePtr = F;
    /* line 27:6 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 27;
    F.filename = "nimponents.nim";
    var newNimponentJS = constructor_536870957;
    /* line 28:6 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 28;
    var connectedCallbackJS = connectedCallback_536870959;
    /* line 29:6 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 29;
    var disconnectedCallbackJS = disconnectedCallback_536870961;
    /* line 30:6 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 30;
    var adoptedCallbackJS = adoptedCallback_536870963;
    /* line 31:6 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 31;
    var attributeChangedCallbackJS = attributeChangedCallback_536870968;
    /* line 35:9 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 35;
     let clazz = class extends HTMLElement {
  constructor() {
    super();
    if (newNimponentJS)
      newNimponentJS(this);
  }
  connectedCallback() {
    if (connectedCallbackJS)
      connectedCallbackJS(this);
  }
  disconnectedCallback() {
    if (disconnectedCallbackJS)
      disconnectedCallbackJS(this);
  }
  adoptedCallback() {
    if (adoptedCallbackJS)
      adoptedCallbackJS(this);
  }
  attributeChangedCallback(name, oldValue, newValue) {
    if (attributeChangedCallbackJS)
      attributeChangedCallbackJS(name, oldValue, newValue);
  }
};

    /* line 60:23 "/home/monofuel/Documents/src/monofuel34089/nimponents/src/nimponents.nim" */
    F.line = 60;
    customElements.define(toJSStr(elementName_536870955), clazz);
  framePtr = F.prev;

  
}
/* line 9:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */

function constructor_536870916(e_536870917) {
  var F = {procname: "example.constructor", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
  framePtr = F;
    /* line 10:4 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
    F.line = 10;
    F.filename = "example.nim";
    rawEcho([77,121,67,111,109,112,111,110,101,110,116,32,99,114,101,97,116,101,100]);
  framePtr = F.prev;

  
}
/* line 12:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */

function connectedCallback_536870918(e_536870919) {
  var F = {procname: "example.connectedCallback", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
  framePtr = F;
    /* line 13:18 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
    F.line = 13;
    F.filename = "example.nim";
    e_536870919.innerHTML = "<p>Hello from MyComponent2</p>";
  framePtr = F.prev;

  
}
/* line 15:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */

function disconnectedCallback_536870920(e_536870921) {
  var F = {procname: "example.disconnectedCallback", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
  framePtr = F;
    /* line 16:4 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
    F.line = 16;
    F.filename = "example.nim";
    rawEcho([77,121,67,111,109,112,111,110,101,110,116,32,100,105,115,99,111,110,110,101,99,116,101,100]);
  framePtr = F.prev;

  
}
/* line 18:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */

function adoptedCallback_536870922(e_536870923) {
  var F = {procname: "example.adoptedCallback", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
  framePtr = F;
    /* line 19:4 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
    F.line = 19;
    F.filename = "example.nim";
    rawEcho([77,121,67,111,109,112,111,110,101,110,116,32,97,100,111,112,116,101,100]);
  framePtr = F.prev;

  
}
/* line 21:5 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */

function attributeChangedCallback_536870924(e_536870925, name_536870926, oldValue_536870927, newValue_536870928) {
  var F = {procname: "example.attributeChangedCallback", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
  framePtr = F;
    /* line 22:4 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
    F.line = 22;
    F.filename = "example.nim";
    rawEcho([77,121,67,111,109,112,111,110,101,110,116,32,97,116,116,114,105,98,117,116,101,32,99,104,97,110,103,101,100,58,32], name_536870926, [32], oldValue_536870927, [32], newValue_536870928);
  framePtr = F.prev;

  
}
var F = {procname: "module example", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
framePtr = F;
/* line 25:14 "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim" */
F.line = 25;
F.filename = "example.nim";
setupNimponent_536870953([109,121,45,99,111,109,112,111,110,101,110,116], constructor_536870916, connectedCallback_536870918, disconnectedCallback_536870920, adoptedCallback_536870922, attributeChangedCallback_536870924);
framePtr = F.prev;
var F = {procname: "module example", prev: framePtr, filename: "/home/monofuel/Documents/src/monofuel34089/nimponents/examples/example.nim", line: 0};
framePtr = F;
framePtr = F.prev;
